#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* speechapi
* Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMTokenTimestamp.h"
@protocol CMTokenTimestamp;
@class CMTokenTimestamp;



@protocol CMSpeechRecognitionResult
@end

@interface CMSpeechRecognitionResult : CMObject

/* Recognition result in text format [optional]
 */
@property(nonatomic) NSString* textResult;
/* Token-level timestamps with character offsets into TextResult [optional]
 */
@property(nonatomic) NSArray<CMTokenTimestamp>* timestamps;

@end
