#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* speechapi
* Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMTextToSpeechRequest
@end

@interface CMTextToSpeechRequest : CMObject

/* Text to be converted to speech [optional]
 */
@property(nonatomic) NSString* text;
/* File format for output audio file: wav or mp3, default is mp3 [optional]
 */
@property(nonatomic) NSString* format;
/* ISO 639-3 three-letter language code (e.g. eng, spa, fra, hin, ita, jpn, por, zho). Default is eng (English). [optional]
 */
@property(nonatomic) NSString* languageCode;
/* Voice gender: Male or Female. Default is Female. Note: Male is not available for French and Chinese. [optional]
 */
@property(nonatomic) NSString* gender;

@end
