#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* speechapi
* Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMTokenTimestamp
@end

@interface CMTokenTimestamp : CMObject

/* The token text (word or subword) [optional]
 */
@property(nonatomic) NSString* token;
/* Start character offset (0-based) in TextResult [optional]
 */
@property(nonatomic) NSNumber* characterOffsetStart;
/* End character offset (exclusive) in TextResult [optional]
 */
@property(nonatomic) NSNumber* characterOffsetEnd;
/* Start time of this token in the audio, in milliseconds [optional]
 */
@property(nonatomic) NSNumber* startTimeMs;
/* End time of this token in the audio, in milliseconds [optional]
 */
@property(nonatomic) NSNumber* endTimeMs;

@end
