#import <Foundation/Foundation.h>
#import <JSONModel/JSONValueTransformer.h>

/**
* barcodeapi
* Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface JSONValueTransformer (ISO8601)

@end
