#import <Foundation/Foundation.h>
#import "CMSpeechRecognitionResult.h"
#import "CMApi.h"

/**
* speechapi
* Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMRecognizeApi: NSObject <CMApi>

extern NSString* kCMRecognizeApiErrorDomain;
extern NSInteger kCMRecognizeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Recognize audio input as text using Advanced AI
/// Uses advanced AI to convert input audio to text. Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats. Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.
///
/// @param languageCode ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional) (default to )
/// @param recognitionMode Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional) (default to Normal)
/// @param speechFile  (optional)
/// 
///  code:200 message:"OK"
///
/// @return CMSpeechRecognitionResult*
-(NSURLSessionTask*) speechRecognizeFilePostWithLanguageCode: (NSString*) languageCode
    recognitionMode: (NSString*) recognitionMode
    speechFile: (NSURL*) speechFile
    completionHandler: (void (^)(CMSpeechRecognitionResult* output, NSError* error)) handler;



@end
