#import <Foundation/Foundation.h>
#import "CMSpeechRecognitionResult.h"
#import "CMApi.h"

/**
* speechapi
* Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMRecognizeApi: NSObject <CMApi>

extern NSString* kCMRecognizeApiErrorDomain;
extern NSInteger kCMRecognizeApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Recognize audio input as text using machine learning
/// Uses advanced machine learning to convert input audio, which can be mp3 or wav, into text.
///
/// @param speechFile Speech file to perform the operation on.  Common file formats such as WAV, MP3 are supported.
/// 
///  code:200 message:"OK"
///
/// @return CMSpeechRecognitionResult*
-(NSURLSessionTask*) recognizeFileWithSpeechFile: (NSURL*) speechFile
    completionHandler: (void (^)(CMSpeechRecognitionResult* output, NSError* error)) handler;



@end
