#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* speechapi
* Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMSpeakApi: NSObject <CMApi>

extern NSString* kCMSpeakApiErrorDomain;
extern NSInteger kCMSpeakApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Perform text-to-speech on a string
/// Takes as input a string and a file format (mp3 or wav) and outputs a wave form in the appropriate format.
///
/// @param format File format to generate response in; possible values are \&quot;mp3\&quot; or \&quot;wav\&quot;
/// @param text The text you would like to conver to speech.  Be sure to surround with quotes, e.g. \&quot;The quick brown fox jumps over the lazy dog.\&quot;
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) speakPostWithFormat: (NSString*) format
    text: (NSString*) text
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;



@end
