#import <Foundation/Foundation.h>
#import "CMTextToSpeechRequest.h"
#import "CMApi.h"

/**
* speechapi
* Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMSpeakApi: NSObject <CMApi>

extern NSString* kCMSpeakApiErrorDomain;
extern NSInteger kCMSpeakApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Generate audio from text using Advanced AI
/// Converts text to speech using advanced AI. Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese. Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female). Output format is controlled by the Format field (mp3 or wav, default: mp3). Consumes 1 API call per second of generated audio.
///
/// @param body String input request (optional)
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) speechSpeakTextVoiceBasicAudioPostWithBody: (CMTextToSpeechRequest*) body
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;



@end
